"""Build RESULTS_LEDGER.md and RESULTS_LEDGER.csv from the saved certified tables.

Single source of truth for the manuscript.  Generated, never hand-edited: every row
is read back from the archive CSV/JSON it came from, so the ledger cannot drift from
the certified record.  Stage 2B's rulings are applied where they change which number
is the result.
"""
import csv, json, math, os, tempfile
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))

# ============================================================ markdown generation
def _tbl(rs, cols):
    out = ["| " + " | ".join(cols) + " |",
           "|" + "|".join("---" for _ in cols) + "|"]
    for r in rs:
        out.append("| " + " | ".join(str(r.get(c, "")).replace("|", "\\|")
                                     for c in cols) + " |")
    return "\n".join(out)


def _fmt_sci(x):
    """1.52241e-24 -> '1.52 x 10^-24' in the document's notation."""
    e = int(math.floor(math.log10(abs(x))))
    return f"{x / 10 ** e:.2f} \u00d7 10{str(e).translate(_SUP)}"


_SUP = str.maketrans("-0123456789", "\u207b\u2070\u00b9\u00b2\u00b3\u2074\u2075\u2076\u2077\u2078\u2079")


def _prose_numbers(rows):
    """Pull the narrative's figures out of the ledger rows themselves, so section 3
    cannot drift from the table underneath it."""
    out = {}
    for r in rows:
        q = r["quantity"]
        if r["item"] == "P4" and "FLOOR-CORRECTED" in q:
            for lam, key in (("1.6", "fc160"), ("1.75", "fc175"), ("1.9", "fc190")):
                if f"lambda = {lam} " in q:
                    unc = r["interval_on_diff"].split(" (h;")[0].replace("+-", "\u00b1 ")
                    out[key] = f"{r['measured']} {unc}"
        if r["item"] == "A6 multiple testing" and q.startswith("Holm-adjusted endpoint "
                                                              "p-value for P4"):
            out["holmB"] = _fmt_sci(float(r["measured"]))
            tail = r["interval_on_diff"].rsplit("Holm ", 1)[-1]
            out["holmA"] = _fmt_sci(float(tail))
    missing = {"fc160", "fc175", "fc190", "holmB", "holmA"} - set(out)
    assert not missing, f"prose numbers not found in rows: {sorted(missing)}"
    return out


def write_markdown(rows, path):
    tot = Counter(r["status"] for r in rows)
    _p = _prose_numbers(rows)
    rep = sum(v for k, v in tot.items() if k.startswith("REPORTED"))
    wdr = sum(v for k, v in tot.items() if k.startswith("WITHDRAWN"))
    by = defaultdict(Counter)
    for r in rows:
        by[(r["stage"], r["item"])][r["status"]] += 1
    L = ["""# CROWD-1 — RESULTS LEDGER

**Single source of truth for the manuscript.** Generated by `build_ledger.py`, never
hand-edited: every row is read back from the certified table or raw JSON in the
archive named in its last column, so the ledger cannot drift from the certified
record. Regenerate with `python build_ledger.py`.

**Stages 1, 2, 2B and 3 are complete.** Stage 3's five items: P5, P7, P9 certified;
P8 reported as a censored supplement with no verdict; **P10 withdrawn, not run**
(§5).

Specification: `review_packet_v0_6_1.md`, memo section "PROCESS SPECIFICATION v0.6".
Design: `crowd1_cs_design_and_manuscript_brief_v0_3_1.md`, Part A (supersedes v0.3).
Appendices E and F: `crowd1_appendices_EF_C7_C9.md` (C7-C9).
""",
         f"""
## 1. Status at a glance

{len(rows)} ledger rows: **{tot['PASS']} PASS, {tot['FAIL']} FAIL, {tot['INCONCLUSIVE']} INCONCLUSIVE**, {rep} reported without a verdict, {wdr} withdrawn.

| stage / item | rows | outcome |
|---|---|---|"""]
    for k in sorted(by):
        c = by[k]
        desc = ", ".join(f"{v} {s}" for s, v in sorted(c.items(), key=lambda x: -x[1]))
        nm = k[0] if k[0].startswith("Stage 1") else f"{k[0]} — {k[1]}"
        L.append(f"| {nm} | {sum(c.values())} | {desc} |")
    L.append("""
## 2. The three Stage 2B rulings, as applied here

1. **P1-delay** — the paper's quantity is the **time-dependent first-generation
   ratio**; the frozen-background proxy appears under its own name and is never the
   result. Discrepancy category **E (estimand mismatch)**, introduced in Stage 2B and
   distinct from B (bug), A (prediction error) and M (model failure). The registered
   sentence "the order advantage is present at every delay" stays failed in the record
   for the proxy and is replaced for the time-dependent count.
2. **P4** — `f_c` from the independent kinetic reference is the reference value.
   Appendix F's `f_c` values and its 0.75 prefactor are **withdrawn**. Category **A**:
   two independent computations of the model agree with each other and the registered
   number disagrees with both.
3. **P6 case B** — certified at the **declared trajectory marker A = 0.325**, which
   the ruling states is *not* "half fold activity". Appendix F's 25.38 stays an
   unverified numerical reference and is not compared; 20.35 is the bridge-fold
   hazard, a different object.

## 3. The five exception rows

Everything else with a verdict PASSES. These five are the entire non-PASS record, all
in Stage 2, and all remain in the record unchanged.

| item | quantity | measured | registered | status | resolution |
|---|---|---|---|---|---|
| P4 | f_c at λ = 1.75 | 0.043815 | 0.038 ± 0.001 | **FAIL** | Category **A**; Stage 2B kinetic reference gives {fc175}, Appendix F withdrawn |
| P4 | f_c at λ = 1.90 | 0.007310 | 0.0086 ± 0.0008 | **FAIL** | Category **A**; kinetic reference {fc190}, Appendix F withdrawn |
| P4 | f_c at λ = 1.60 | 0.133422 | 0.1270 ± 0.0020 | INCONCLUSIVE | Same; kinetic reference {fc160} |
| P1-delay | advantage present at every delay | 1.0006 at τ₀ = 0 | > 1 | INCONCLUSIVE | Category **E**; the proxy's ratio is *exactly* 1 at τ₀ = 0 by R8(b). Replaced by the time-dependent ratio, 1.275 → 1.963 |
| P2-delay | ρ = 0 order dependence persists | spread 0.006199 | persists | INCONCLUSIVE | Secondary endpoint; needs ≈ 2.9 × 10⁵ backgrounds at δ = 2 % of 0.006199 |

The three kinetic references above are the FLOOR-CORRECTED values (c_min 10⁻³ → 10⁻⁵,
`REPORT_floor_audit.md`); the h error beside each is unchanged, because the floor shift
is independent of h.

**Holm across the six Stage 2 primary endpoints (P1, P1-delay, P2, P3, P4, P6),
owner ruling S2B-A6 reading B** — endpoint p = min(1, m × min row p), then Holm:
only **P4** rejects, adjusted p = {holmB}; the other five have adjusted p = 1.
Under the superseded reading A (bare minimum row p-value, as originally run) P4's
adjusted p was {holmA}; the selection is the same under both.

## 4. Full table, one row per certified result
""".format(**_p))
    for stage in ["Stage 1", "Stage 2", "Stage 2B", "Stage 3 P5", "Stage 3 P7",
                  "Stage 3 P9", "Stage 3 P8", "Stage 3 P10"]:
        rs = [r for r in rows if r["stage"] == stage]
        if not rs:
            continue
        L.append(f"\n### {stage} — {len(rs)} rows\n")
        L.append(_tbl(rs, ["item", "quantity", "predicted", "measured", "diff",
                           "interval_on_diff", "delta", "status", "category", "N",
                           "replicates"]))
    L.append("""

## 5. P10 — withdrawn, not run

Withdrawn by the owner on 2026-10-02:

> "P10 withdrawn from Stage 3: the registered lag window is empty at h = 0.1 and
> 0.05; the Lux coefficient map stays in the manuscript as a derived closure without
> numerical certification."

**Reason.** The Stage 3 estimand measures H and J from the conviction drift and D from
the lagged increment variance over lags in [5/(ρ+κ), 0.1/ε]. Under the R10 map
ρ = p₀/h and κ = k₀/h, so the lower edge is 5h/2 against a fixed upper edge of 0.1/ε:
the window is [0.2500, 0.1000] at h = 0.1 and [0.1250, 0.1000] at h = 0.05, both
**empty**, and non-empty only for h ≤ 0.04 — one point of the registered grid, which
leaves nothing to check the O(h) convergence against.

**Manuscript disposition.** The Lux coefficient map stays in the manuscript as a
**derived closure without numerical certification**. Its derivation is algebraically
confirmed: recomputing from Appendix C C6.1/C6.5/C6.6 reproduces the registered
H = 2.5 exactly and J = 0.8 to 2 × 10⁻¹⁶, with D, J/D and K agreeing to the rounding
of their registered three- and four-figure values. Both wall-pinning conditions hold
(C6.8: H > ε; C6.9: H − |Jx| > ε for all |x| ≤ 1), and K = 1.46 confirms this is not a
deep-well regime, so no switching-exponent comparison was ever in scope. See
`stage3/P10/README.md` and `stage3/P10/outputs/p10_map_check.json`. **No simulation
was run and no number is numerically certified.**

## 6. Open items

Every registered item is now either certified, reported, or withdrawn. What remains
open is inherited from the appendices, not from the simulation programme.

| item | status | what it needs |
|---|---|---|
| Appendix F's 25.38 (P6 case B) | unverified | Its provenance is known (Appendix F's own `Λ exact` column, by simulation at M = 2 × 10⁴) but it is not independently reproduced: the kinetic Λ* is 25.42849 ± 0.01344, differing by 3.6 × the numerical uncertainty. |
| Appendix F's 0.75 prefactor (P4) | withdrawn, unexplained | No quantity computed in this project carries it: `f_c^MF / A_u` = 0.9425, 0.7721, 0.5846 at λ = 1.60, 1.75, 1.90 and is not constant. |
| P4 `f_c` near λ_fold, and the exact prefactor | OPEN | Listed OPEN by Appendix F itself. |
| C7's uniform fold-time theorem | OPEN | Listed OPEN by Appendices E and F. |
| P10's gated O(h) correction and skewness coefficient | OPEN | Listed OPEN by R10 and Appendix C C6; out of scope now that P10 is withdrawn. |

## 7. Archive versions

| archive | contents |
|---|---|
| `crowd1_stage1_archive_v3` | A1 implementation, T1-T6, 124 rows |
| `crowd1_stage2_archive` (s2-v2) | P1, P1-delay, P2, P2-delay, P3, P4, P6, 37 rows + Holm |
| `crowd1_stage2b_archive` | P1-delay audit, P4 kinetic reference, P6 case B reference and verdict |
| `crowd1_stage3_P5_archive` | P5, 6 rows |
| `crowd1_stage3_P7_archive` | P7, 36 rows |
| `crowd1_stage3_P9_archive` | P9, 18 rows |
| `crowd1_stage3_P8_archive` | P8, censored supplement, 4 reported rows |
| `crowd1_stage3_P10_archive` | P10, withdrawn: the algebraic map check only |

Master seeds, one per stage/item, all distinct: 20261001 (Stage 1), 20261002 (Stage 2
and 2B), 20261003 (P5), 20261004 (P7), 20261005 (P9), 20261006 (P8). P10 ran no
simulation and has no seed.
""")
    with open(path, "w") as fh:
        fh.write("\n".join(L))


SRC = [
    ("Stage 1", "crowd1_stage1_archive_v3", "stage1/outputs/certified_table.csv"),
    ("Stage 2", "crowd1_stage2_archive (s2-v2)", "stage2/outputs/certified_table.csv"),
    ("Stage 3 P5", "crowd1_stage3_P5_archive", "stage3/P5/outputs/certified_table.csv"),
    ("Stage 3 P7", "crowd1_stage3_P7_archive", "stage3/P7/outputs/certified_table.csv"),
    ("Stage 3 P9", "crowd1_stage3_P9_archive", "stage3/P9/outputs/certified_table.csv"),
]
rows = []
for stage, archive, path in SRC:
    with open(os.path.join(HERE, path)) as fh:
        for r in csv.DictReader(fh):
            iv = ""
            try:
                lo, hi = float(r["ci_lo"]), float(r["ci_hi"])
                iv = f"[{lo:+.4g}, {hi:+.4g}]"
            except (ValueError, KeyError):
                pass
            rows.append(dict(
                stage=stage, item=r.get("endpoint") or stage.split()[-1],
                quantity=r["name"], predicted=r["predicted"], measured=r["measured"],
                diff=r["diff"], interval_on_diff=iv, delta=r["delta"],
                status=r["status"], category="", archive=archive,
                N=r.get("N", ""), replicates=r.get("n_replicates", "")))

# ---- Stage 2B: the three rulings, as ledger rows
S2B = json.load(open(os.path.join(HERE, "stage2b/outputs/raw/p1delay_reference.json")))
P4R = json.load(open(os.path.join(HERE, "stage2b/outputs/raw/p4_reference.json")))
P6V = json.load(open(os.path.join(HERE, "stage2b/outputs/raw/p6b_verdict.json")))
taus = S2B["delays"]
md = {r["tau0"]: r for r in S2B["measured_ratio"] if r["relax_rho"] == 1.0}
mf = {r["tau0"]: r for r in S2B["measured_ratio"] if r["relax_rho"] == 0.0}
for i, t in enumerate(taus):
    rows.append(dict(
        stage="Stage 2B", item="P1-delay",
        quantity=f"between-order ratio of the time-dependent first-generation count "
                 f"E Z1 at tau0 = {t}/rho  [THE RESULT, per ruling 1]",
        predicted=f"{S2B['reference_ratio_time_dependent'][i]:.7f}",
        measured=f"{md[t]['ratio']:.5f}", diff="",
        interval_on_diff=f"+-{md[t]['ratio_sem']:.5f} (sem over 24 backgrounds)",
        delta="", status="REPORTED (replaces the failed registered sentence)",
        category="E (estimand mismatch)", archive="crowd1_stage2b_archive",
        N="100000", replicates="24 backgrounds x 10000 trials"))
for i, t in enumerate(taus):
    rows.append(dict(
        stage="Stage 2B", item="P1-delay",
        quantity=f"between-order ratio of the FROZEN-BACKGROUND PROXY at "
                 f"tau0 = {t}/rho  [named as a proxy, not the result]",
        predicted=f"{S2B['reference_ratio_frozen_proxy'][i]:.7f}",
        measured=f"{mf[t]['ratio']:.5f}", diff="",
        interval_on_diff=f"+-{mf[t]['ratio_sem']:.5f}", delta="",
        status="REPORTED (proxy)", category="E (estimand mismatch)",
        archive="crowd1_stage2b_archive", N="100000",
        replicates="24 backgrounds x 10000 trials"))
FAC = json.load(open(os.path.join(HERE,
                                  "stage2b/outputs/raw/floor_audit_corrections.json")))
_fa = {f"{r['lam']:g}": r for r in FAC["P4"]}
for lam in ("1.6", "1.75", "1.9"):
    k = P4R[lam]
    a = _fa[lam]
    rows.append(dict(
        stage="Stage 2B", item="P4",
        quantity=f"critical fraction f_c at lambda = {lam} from the independent "
                 f"kinetic reference  [THE REFERENCE VALUE, per ruling 2; "
                 f"FLOOR-CORRECTED, c_min 1e-3 -> 1e-5]",
        predicted="(Appendix F value WITHDRAWN)",
        measured=f"{a['corrected']:.6f}", diff="",
        interval_on_diff=f"+-{a['unc_h']:.2e} (h; horizon sensitivity 0) "
                         f"+-{a['floor_error']:.2e} (floor)",
        delta="", status="REPORTED (reference)",
        category=f"A (error in the registered prediction). Floor shift "
                 f"{a['floor_shift']:+.3e}, h-independent to "
                 f"{a['h_independence_of_shift']:.1e}; supersedes the floor-1e-3 "
                 f"value {k['f_c_richardson']:.6f}. Still overlaps the agent f_50 "
                 f"interval: {a['overlaps_agent']}; still disjoint from the "
                 f"withdrawn Appendix F value: {a['disjoint_from_appendixF']}. "
                 f"No verdict attached to this row, and none changed.",
        archive="crowd1_stage2b_archive", N="mean field (N -> inf)", replicates="-"))
# P6 floor audit: case A NEITHER corrected NOR bounded (no bound on its floor error is
# claimed anywhere), case B corrected.  No verdict changes either way.
rows.append(dict(
    stage="Stage 2B", item="P6 case A",
    quantity="t_dagger at A_f = 0.5603, kinetic reference: FLOOR AUDIT",
    predicted="70.3 +- 0.1 (registered)",
    measured=f"{FAC['P6A']['published']:.6f} (unchanged)", diff="",
    interval_on_diff=f"+-{FAC['P6A']['unc_h']:.6f} (h) ; matched-h floor shift over "
                     f"c_min 1e-2 -> 1e-4 ONLY = {FAC['P6A']['matched_floor_effect']:+.3e} "
                     f"({FAC['P6A']['pct_of_h_error']:.2f}% of the h error); the "
                     f"2e-2 -> 1e-2 step is not quantified, so this is a measured "
                     f"partial shift, NOT a bound on the floor error",
    delta="", status="REPORTED (floor audit, no verdict)",
    category=("floor as run 2e-2, 20x coarser than the default. NO BOUND IS CLAIMED "
              "on the total floor effect: the matched-h shift from c_min 1e-2 to 1e-4 "
              "is MEASURED at +1.371e-4, but the 2e-2 -> 1e-2 step -- the one that "
              "separates the floor actually used from the measured range -- is NOT "
              "quantified, because 2e-2 is not commensurate with 1e-2 and 1e-4 "
              "(U2/U1 = 2 exactly there) and an unmatched comparison is confounded by "
              "the adjusted h. t_dagger is reported unchanged at "
              "70.327688 +- 0.024355 (h) with the floor contribution UNQUANTIFIED. "
              "Quantifying it needs a floor ladder at every rung of the h-ladder "
              "(436 counter slabs at c_min = 1e-4); deliberately not run."),
    archive="crowd1_stage2b_archive", N="mean field (N -> inf)", replicates="-"))
for nm, kk in (("t_star", "t*"), ("Lambda_star", "Lambda*")):
    b = FAC["P6B"][nm]
    rows.append(dict(
        stage="Stage 2B", item="P6 case B",
        quantity=f"{kk} at A = 0.325, kinetic reference [FLOOR-CORRECTED, "
                 f"c_min 1e-2 -> 1e-4, matched h]",
        predicted="(no registered value; this is the reference)",
        measured=f"{b['corrected']:.6f}", diff="",
        interval_on_diff=f"+-{b['unc_h']:.6f} (h) +-<1e-7 (floor)",
        delta="", status="REPORTED (reference)",
        category=f"matched-h floor effect {b['matched_floor_effect']:+.3e}; "
                 f"supersedes the floor-1e-2 value {b['published']:.6f}. The case B "
                 f"PASS verdicts were re-checked against the corrected value and "
                 f"both still PASS.",
        archive="crowd1_stage2b_archive", N="mean field (N -> inf)", replicates="-"))
# ---- A6 multiple-testing and sampling, per the owner rulings of 2026-10-02.
# S2B-A6: A6 mandates Holm across the six primary endpoints but does not define an
# endpoint p-value.  RULED: reading B -- Bonferroni-adjust the minimum row p-value
# within each endpoint, then Holm across the six.  Recomputed from the Stage 2
# per-row equivalence p-values; the selection is unchanged (P4 only).
S2RES = json.load(open(os.path.join(HERE, "stage2/outputs/stage2_results.json")))
_PRIM = ["P1", "P1-delay", "P2", "P3", "P4", "P6"]
_pmin, _m = {}, {}
for r in S2RES["certified_table"]:
    e = r.get("endpoint")
    if e in _PRIM and r.get("p_equivalence") is not None:
        _pmin[e] = min(_pmin.get(e, 1.0), float(r["p_equivalence"]))
        _m[e] = _m.get(e, 0) + 1


def _holm(ps):
    order = sorted(range(len(ps)), key=lambda i: ps[i])
    adj, run = [0.0] * len(ps), 0.0
    for k, i in enumerate(order):
        run = max(run, (len(ps) - k) * ps[i])
        adj[i] = min(1.0, run)
    return adj


_pB = [min(1.0, _m[e] * _pmin[e]) for e in _PRIM]
_aB = _holm(_pB)
_pA = [_pmin[e] for e in _PRIM]
_aA = _holm(_pA)
for e, m, pa, aa, pb, ab in zip(_PRIM, [_m[x] for x in _PRIM], _pA, _aA, _pB, _aB):
    rows.append(dict(
        stage="Stage 2", item="A6 multiple testing",
        quantity=f"Holm-adjusted endpoint p-value for {e} ({m} rows), RULED reading B: "
                 f"p_endpoint = min(1, m * min_row_p), then Holm across the six "
                 f"primary endpoints",
        predicted="(no predicted value; this is the pass rule, not a quantity)",
        measured=f"{ab:.6g}", diff="",
        interval_on_diff=f"superseded reading A (bare min_row_p, as originally run): "
                         f"endpoint p {pa:.6g}, Holm {aa:.6g}",
        delta="reject at 0.05", status="REPORTED (pass rule, no verdict)",
        category=("rejects at 0.05 under both readings"
                  if ab < 0.05 else "does not reject at 0.05 under either reading"),
        archive="crowd1_stage2_archive", N="-",
        replicates=f"{m} registered rows in this endpoint"))
# S2B-A7: RULED -- disclose the sampling design as run.  No number changes.
rows.append(dict(
    stage="Stage 2", item="A6 sampling design",
    quantity="replicate-count rule and interval construction actually used across "
             "Stage 2 and Stage 3",
    predicted="(A6 is silent on the sample-size rule and on pooling)",
    measured="pilot of 50; need = ceil((1.96/target)^2 * max(p_hat*(1-p_hat), "
             "floor_var)) then need = min(max(need, pilot), cap); target = 0.03 and "
             "floor_var = 0.01 for P1 (_p1_pop), target = 0.02 and floor_var = 0.004 "
             "for P2 (_generic_pop); pilot = 50, CAP = 1200 replicates. The PILOT IS "
             "POOLED into every reported estimate; fixed-sample Wilson and t "
             "intervals throughout",
    diff="",
    interval_on_diff="final sample size is data-dependent through need(p_hat from the "
                     "pilot), so fixed-sample nominal coverage is not automatic. The "
                     "cap never bound: the largest realized count anywhere is 1157. "
                     "The N = 1e6 diagnostic cells at lambda = 2 are OUTSIDE this "
                     "rule: fixed 50-run design, not piloted and not extended, no "
                     "precision target and no meets_target flag; the adaptive rule "
                     "at the realised 18/50 would have asked for 984 replicates",
    delta="-", status="REPORTED (disclosure, no verdict)",
    category="coverage under the realized adaptive design NOT ASSESSED; replicate "
             "counts and the meets_target flags are reported beside every number. "
             "A 0/50 cell has Wilson interval [0, 0.071348]: upper endpoint 0.071348, "
             "HALF-WIDTH 0.035674. The half-width is the quantity the A4a targets "
             "bound and it exceeds both, 0.0357 > 0.03 (P1) and > 0.02 (P2). Such "
             "cells are never extended, because the variance floor gives need = 43 "
             "(P1) / 39 (P2) < pilot when p_hat = 0",
    archive="crowd1_stage2_archive, crowd1_stage3_* archives", N="-",
    replicates="50 pilot, extended per item to at most the cap"))

# ---- precision-target reconciliation for the adaptive outbreak cells.
# The flags are correct as recorded; what is reconciled here is that the rule SIZES
# for +-0.03 from the pilot and does not guarantee it, so three extended cells miss.
TREC = json.load(open(os.path.join(HERE,
                                   "stage2b/outputs/raw/outbreak_target_reconciliation.json")))
for t in TREC:
    rows.append(dict(
        stage="Stage 2", item="A6 sampling design",
        quantity=f"realised precision for {t['prediction']} {t['order']}: Wilson "
                 f"half-width against the +-{t['target']} A4a target",
        predicted=f"target half-width {t['target']}",
        measured=f"{t['wilson_half_width']:.6f}  ({t['outbreaks']}/{t['replicates']}, "
                 f"p_hat = {t['p_hat_final']:.6f})",
        diff=f"{t['wilson_half_width'] - t['target']:+.6f}",
        interval_on_diff=f"pilot {t['pilot_outbreaks']}/50 sized need = "
                         f"{t['replicates']}; at the realised p_hat the rule would "
                         f"have asked for {t['n_needed_at_realized_p']} "
                         f"({t['shortfall']:+d})",
        delta=f"{t['target']}",
        status="REPORTED (disclosure, no verdict)",
        category=("TARGET MET" if t["meets_target"] else
                  "TARGET MISSED: need is computed once from the pilot's p_hat and "
                  "never revised, and the realised p_hat(1-p_hat) came out above the "
                  "pilot's estimate") +
                 f"; meets_target flag recorded as {t['meets_target']}; cap 1200 not "
                 f"reached",
        archive="crowd1_stage2_archive", N="100000",
        replicates=f"{t['replicates']} (50 pilot pooled + extension)"))

# ---- class-2 fold (alpha = 0.5, c_b = 0.3, eps = 1, r = 1).
# EXACT: the C2.11-C2.14 stationary law, which closes after two method-of-steps
# intervals at alpha = 0.5.  Supersedes the measure-solver route, which was biased by
# an unladdered conviction floor -- BUGLOG S2B-4.  No tolerance is registered for
# these three numbers in design A4/A4a, so they carry no verdict.
FLD = json.load(open(os.path.join(HERE, "stage2b/outputs/raw/fold_exact.json")))
_fx, _ne = FLD["fold"], FLD["fold"]["numerical_error"]
_dv = FLD["fold"]["deviation_from_manuscript"]
for key, label in (("lam_fold", "lambda_fold"), ("nu_f", "nu_f"),
                   ("A_fold", "A_fold")):
    man = FLD["manuscript"][key]
    rows.append(dict(
        stage="Stage 2B", item="class-2 fold",
        quantity=f"{label} of the class-2 fold at alpha = 0.5, c_b = 0.3, eps = 1, "
                 f"r = 1, from min_nu nu/P_nu on the EXACT C2.11-C2.14 stationary law",
        predicted=f"{man} (manuscript figure, no registered tolerance)",
        measured=f"{_fx[key]:.9f}", diff=f"{_dv[key]:+.2e}",
        interval_on_diff=f"+-{_ne[key]:.1e} (Gauss-Legendre node ladder, "
                         f"{FLD['node_ladder'][-1]['nodes']} nodes)",
        delta="(none registered)",
        status="REPORTED (no registered tolerance)",
        category=("agrees with the manuscript to its printed precision; supersedes "
                  "the measure-solver value, BUGLOG S2B-4 category B"),
        archive="crowd1_stage2b_archive", N="mean field (N -> inf)", replicates="-"))
for v in P6V["verdicts"]:
    rows.append(dict(
        stage="Stage 2B", item="P6 case B",
        quantity=v["name"] + "  [declared trajectory marker, per ruling 3]",
        predicted=f"{v['predicted']:.5f}", measured=f"{v['measured']:.5f}",
        diff=f"{v['diff']:+.5f}",
        interval_on_diff=f"[{v['ci_lo']:+.5f}, {v['ci_hi']:+.5f}]",
        delta=f"{v['delta']:.5f}", status=v["status"], category="",
        archive="crowd1_stage2b_archive", N=str(v["N"]),
        replicates=str(v["n_replicates"])))
# ---- P10: withdrawn, not run (owner 2026-10-02)
P10 = json.load(open(os.path.join(HERE, "stage3/P10/outputs/p10_map_check.json")))
rows.append(dict(
    stage="Stage 3 P10", item="P10",
    quantity="Lux coefficient map (H, J, D) measured from conviction drift and "
             "lagged increment variance on the active branch",
    predicted=f"H = {P10['registered']['H']}, J = {P10['registered']['J']}, "
              f"D = {P10['registered']['D']}",
    measured="NOT MEASURED - no simulation was run",
    diff="", interval_on_diff="", delta="delta = 2% (never applied)",
    status="WITHDRAWN, NOT RUN", category="",
    archive="crowd1_stage3_P10_archive", N="-", replicates="-"))
rows.append(dict(
    stage="Stage 3 P10", item="P10",
    quantity="algebraic check of the registered coefficients against Appendix C "
             "C6.1/C6.5/C6.6  [derivation check, NOT a numerical certification]",
    predicted=f"H = {P10['registered']['H']}, J = {P10['registered']['J']}, "
              f"D = {P10['registered']['D']}",
    measured=f"H = {P10['computed']['H']:.9f}, J = {P10['computed']['J']:.9f}, "
             f"D = {P10['computed']['D']:.9f}",
    diff=f"H {P10['deviation']['H']:+.1e}, J {P10['deviation']['J']:+.1e}, "
         f"D {P10['deviation']['D']:+.1e} (rounding of the registered figures)",
    interval_on_diff="", delta="",
    status="REPORTED (derivation check, no verdict)", category="",
    archive="crowd1_stage3_P10_archive", N="mean field, h -> 0", replicates="-"))

# ---- P8: reported, no verdict
P8 = json.load(open(os.path.join(HERE, "stage3/P8/outputs/p8_results.json")))
for r in P8["rows"]:
    rows.append(dict(
        stage="Stage 3 P8", item="P8",
        quantity=f"median extinction time at N = {r['N']} (right-censored at "
                 f"T_max = 2000)",
        predicted="no number registered", measured=r["median_extinction_time"],
        diff="", interval_on_diff=f"{r['n_extinct']}/{r['replicates']} extinguished",
        delta="", status="REPORTED (no verdict)", category="",
        archive="crowd1_stage3_P8_archive", N=str(r["N"]),
        replicates=str(r["replicates"])))

# =========================================================== CROWD-2, appended
# Authorization "Crowd-2 Stage 2 authorization (2026-10-02)": "Crowd-1's
# communication core, engine and RESULTS_LEDGER.md are unchanged; Crowd-2 rows
# are appended to the same ledger with prefix C2-."  CROWD-1's rows and CROWD-1's
# markdown are therefore produced exactly as before and the CROWD-2 rows are
# APPENDED after them, so every byte of the CROWD-1 ledger is a prefix of the
# combined file.  Nothing above this line was changed.
C2DIR = os.path.join(HERE, "crowd2", "outputs")
c2_rows = []
if os.path.isdir(C2DIR):
    C2SRC = [("Crowd-2 Stage 2A", "crowd2_stage2a_archive",
              "stage2a_certified_table.csv"),
             ("Crowd-2 Stage 2B", "crowd2_stage2b_archive",
              "stage2b_certified_table.csv")]
    for stage, archive, fn in C2SRC:
        p = os.path.join(C2DIR, fn)
        if not os.path.exists(p):
            continue
        with open(p) as fh:
            for r in csv.DictReader(fh):
                iv = ""
                try:
                    iv = f"[{float(r['ci_lo']):+.4g}, {float(r['ci_hi']):+.4g}]"
                except (ValueError, KeyError):
                    pass
                nm = r["name"]
                # "C2-xx ..." -> item "C2-xx"; the one sweep-design row that is
                # not a numbered acceptance test keeps its own section label,
                # prefixed per the authorization.
                item = nm.split()[0] if nm.startswith("C2-") else "C2-" + nm.split()[0]
                c2_rows.append(dict(
                    stage=stage, item=item, quantity=nm,
                    predicted=r["predicted"], measured=r["measured"],
                    diff=r["diff"], interval_on_diff=iv, delta=r["delta"],
                    status=r["status"], category="", archive=archive,
                    N=r.get("N", ""), replicates=r.get("n_replicates", "")))
    # C2-02 is a regression over the whole CROWD-1 Stage 1 suite, reported as one row
    p02 = os.path.join(C2DIR, "c2_02_regression.json")
    if os.path.exists(p02):
        J = json.load(open(p02))
        c2_rows.insert(0, dict(
            stage="Crowd-2 Stage 2A", item="C2-02",
            quantity=f"all {J['rows_in_stage1_archive']} CROWD-1 Stage 1 rows "
                     f"re-run on the CROWD-2 engine, market layer present, source "
                     f"disarmed, positions logged",
            predicted="every verdict unchanged",
            measured=f"{J['rows_compared']} rows compared, "
                     f"{len(J['verdict_changes'])} verdict changes, "
                     f"{J['n_numeric_changes']} numeric changes",
            diff="0", interval_on_diff="exact, bitwise", delta="0",
            status=J["bitwise_identical"], category="",
            archive="crowd2_stage2a_archive", N="as CROWD-1 Stage 1",
            replicates="as CROWD-1 Stage 1"))

with open(os.path.join(HERE, "RESULTS_LEDGER.csv"), "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=list(rows[0]))
    w.writeheader(); w.writerows(rows); w.writerows(c2_rows)

write_markdown(rows, os.path.join(HERE, "RESULTS_LEDGER.md"))
if c2_rows:
    c2t = Counter(r["status"] for r in c2_rows)
    by2 = defaultdict(Counter)
    for r in c2_rows:
        by2[(r["stage"], r["item"])][r["status"]] += 1
    with open(os.path.join(HERE, "RESULTS_LEDGER.md"), "a") as fh:
        fh.write("\n\n---\n\n# CROWD-2 — APPENDED ROWS\n\n")
        fh.write("Appended by `build_ledger.py` under the Crowd-2 Stage 2 "
                 "authorization of 2026-10-02, which authorizes memo section 8 "
                 "**D9** (engine extension) and **D2** (single-believer flip "
                 "problem) of `crowd2/claude_crowd2_memo_v0_4.md` and nothing "
                 "else. Everything above this rule is the CROWD-1 ledger, "
                 "unchanged.\n\n")
        fh.write(f"**{len(c2_rows)} rows**: "
                 + ", ".join(f"{v} {k}" for k, v in sorted(c2t.items())) + ".\n\n")
        fh.write("Not run, and not authorized: memo D3-D8, D10, and the "
                 "certification of the D11 controls (smoke-tested only).\n\n")
        for stage in ["Crowd-2 Stage 2A", "Crowd-2 Stage 2B"]:
            rs = [r for r in c2_rows if r["stage"] == stage]
            if not rs:
                continue
            fh.write(f"\n### {stage} — {len(rs)} rows\n\n")
            fh.write(_tbl(rs, ["item", "quantity", "predicted", "measured", "diff",
                               "interval_on_diff", "delta", "status", "category",
                               "N", "replicates"]) + "\n")
print(f"{len(rows)} CROWD-1 ledger rows + {len(c2_rows)} CROWD-2 rows "
      f"-> RESULTS_LEDGER.csv and RESULTS_LEDGER.md")
print("CROWD-1:", Counter(r["status"] for r in rows))
print("CROWD-2:", Counter(r["status"] for r in c2_rows))
